import { create } from 'zustand'
import { persist } from 'zustand/middleware'

// ════════════════════════════════════════════════════════════════
// MULTI-LANGUAGE SUPPORT — SkillSetu
// ════════════════════════════════════════════════════════════════

const TRANSLATIONS = {
  en: {
    _name: 'English',
    _flag: '🇬🇧',
    // Nav
    dashboard: 'Dashboard',
    myProfile: 'My Profile',
    careerRoadmap: 'Career Roadmap',
    resumeBuilder: 'Resume Builder',
    resumeScore: 'Resume Score',
    jobExplorer: 'Job Explorer',
    applications: 'Applications',
    aiTools: 'AI Tools',
    skillGap: 'Skill Gap',
    salaryInsights: 'Salary Insights',
    govtJobs: 'Govt Jobs',
    mockInterview: 'Mock Interview',
    other: 'Other',
    messages: 'Messages',
    myPortfolio: 'My Portfolio',
    // New features
    achievements: 'Achievements',
    careerCompare: 'Career Compare',
    scholarships: 'Scholarships',
    skillQuiz: 'Skill Quiz',
    industryTrends: 'Industry Trends',
    // Common
    search: 'Search',
    submit: 'Submit',
    reset: 'Reset',
    loading: 'Loading...',
    logout: 'Logout',
    settings: 'Settings',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    language: 'Language',
    welcome: 'Welcome back',
    viewAll: 'View All',
  },
  hi: {
    _name: 'हिन्दी',
    _flag: '🇮🇳',
    dashboard: 'डैशबोर्ड',
    myProfile: 'मेरी प्रोफ़ाइल',
    careerRoadmap: 'करियर रोडमैप',
    resumeBuilder: 'रिज़्यूमे बिल्डर',
    resumeScore: 'रिज़्यूमे स्कोर',
    jobExplorer: 'जॉब एक्सप्लोरर',
    applications: 'आवेदन',
    aiTools: 'AI टूल्स',
    skillGap: 'स्किल गैप',
    salaryInsights: 'सैलरी इनसाइट्स',
    govtJobs: 'सरकारी नौकरी',
    mockInterview: 'मॉक इंटरव्यू',
    other: 'अन्य',
    messages: 'संदेश',
    myPortfolio: 'मेरा पोर्टफोलियो',
    achievements: 'उपलब्धियाँ',
    careerCompare: 'करियर तुलना',
    scholarships: 'छात्रवृत्ति',
    skillQuiz: 'स्किल क्विज़',
    industryTrends: 'उद्योग ट्रेंड्स',
    search: 'खोजें',
    submit: 'जमा करें',
    reset: 'रीसेट',
    loading: 'लोड हो रहा है...',
    logout: 'लॉग आउट',
    settings: 'सेटिंग्स',
    darkMode: 'डार्क मोड',
    lightMode: 'लाइट मोड',
    language: 'भाषा',
    welcome: 'स्वागत है',
    viewAll: 'सभी देखें',
  },
  ta: {
    _name: 'தமிழ்',
    _flag: '🇮🇳',
    dashboard: 'டாஷ்போர்டு',
    myProfile: 'என் சுயவிவரம்',
    careerRoadmap: 'தொழில் வழிகாட்டி',
    resumeBuilder: 'ரெசுமே உருவாக்கி',
    resumeScore: 'ரெசுமே மதிப்பெண்',
    jobExplorer: 'வேலை அறிஞர்',
    applications: 'விண்ணப்பங்கள்',
    aiTools: 'AI கருவிகள்',
    skillGap: 'திறன் இடைவெளி',
    salaryInsights: 'சம்பள நுண்ணறிவு',
    govtJobs: 'அரசு வேலைகள்',
    mockInterview: 'போலி நேர்காணல்',
    other: 'மற்றவை',
    messages: 'செய்திகள்',
    myPortfolio: 'என் போர்ட்ஃபோலியோ',
    achievements: 'சாதனைகள்',
    careerCompare: 'தொழில் ஒப்பீடு',
    scholarships: 'உதவித்தொகை',
    skillQuiz: 'திறன் வினாடி வினா',
    industryTrends: 'தொழில்துறை போக்குகள்',
    search: 'தேடு',
    submit: 'சமர்ப்பி',
    reset: 'மீட்டமை',
    loading: 'ஏற்றுகிறது...',
    logout: 'வெளியேறு',
    settings: 'அமைப்புகள்',
    darkMode: 'இருண்ட பயன்முறை',
    lightMode: 'ஒளி பயன்முறை',
    language: 'மொழி',
    welcome: 'மீண்டும் வரவேற்கிறோம்',
    viewAll: 'அனைத்தையும் காண்க',
  },
  te: {
    _name: 'తెలుగు',
    _flag: '🇮🇳',
    dashboard: 'డాష్‌బోర్డ్',
    myProfile: 'నా ప్రొఫైల్',
    careerRoadmap: 'కెరీర్ రోడ్‌మ్యాప్',
    resumeBuilder: 'రెజ్యూమే బిల్డర్',
    resumeScore: 'రెజ్యూమే స్కోర్',
    jobExplorer: 'ఉద్యోగ అన్వేషణ',
    applications: 'దరఖాస్తులు',
    aiTools: 'AI సాధనాలు',
    skillGap: 'నైపుణ్య అంతరం',
    salaryInsights: 'జీతం అంతర్దృష్టులు',
    govtJobs: 'ప్రభుత్వ ఉద్యోగాలు',
    mockInterview: 'మాక్ ఇంటర్వ్యూ',
    other: 'ఇతరాలు',
    messages: 'సందేశాలు',
    myPortfolio: 'నా పోర్ట్‌ఫోలియో',
    achievements: 'సాధనలు',
    careerCompare: 'కెరీర్ పోలిక',
    scholarships: 'స్కాలర్‌షిప్‌లు',
    skillQuiz: 'నైపుణ్య క్విజ్',
    industryTrends: 'పరిశ్రమ ట్రెండ్‌లు',
    search: 'వెతుకు',
    submit: 'సమర్పించు',
    reset: 'రీసెట్',
    loading: 'లోడ్ అవుతోంది...',
    logout: 'లాగ్ అవుట్',
    settings: 'సెట్టింగ్‌లు',
    darkMode: 'డార్క్ మోడ్',
    lightMode: 'లైట్ మోడ్',
    language: 'భాష',
    welcome: 'తిరిగి స్వాగతం',
    viewAll: 'అన్నీ చూడండి',
  },
  bn: {
    _name: 'বাংলা',
    _flag: '🇮🇳',
    dashboard: 'ড্যাশবোর্ড',
    myProfile: 'আমার প্রোফাইল',
    careerRoadmap: 'ক্যারিয়ার রোডম্যাপ',
    resumeBuilder: 'রেজুমে বিল্ডার',
    resumeScore: 'রেজুমে স্কোর',
    jobExplorer: 'চাকরি অনুসন্ধান',
    applications: 'আবেদনসমূহ',
    aiTools: 'AI টুলস',
    skillGap: 'দক্ষতা ফাঁক',
    salaryInsights: 'বেতন অন্তর্দৃষ্টি',
    govtJobs: 'সরকারি চাকরি',
    mockInterview: 'মক ইন্টারভিউ',
    other: 'অন্যান্য',
    messages: 'বার্তা',
    myPortfolio: 'আমার পোর্টফোলিও',
    achievements: 'অর্জনসমূহ',
    careerCompare: 'ক্যারিয়ার তুলনা',
    scholarships: 'বৃত্তি',
    skillQuiz: 'দক্ষতা কুইজ',
    industryTrends: 'শিল্প প্রবণতা',
    search: 'অনুসন্ধান',
    submit: 'জমা দিন',
    reset: 'রিসেট',
    loading: 'লোড হচ্ছে...',
    logout: 'লগ আউট',
    settings: 'সেটিংস',
    darkMode: 'ডার্ক মোড',
    lightMode: 'লাইট মোড',
    language: 'ভাষা',
    welcome: 'স্বাগতম',
    viewAll: 'সব দেখুন',
  },
}

export const LANGUAGES = Object.keys(TRANSLATIONS).map(code => ({
  code,
  name: TRANSLATIONS[code]._name,
  flag: TRANSLATIONS[code]._flag,
}))

export const useLanguageStore = create(
  persist(
    (set, get) => ({
      lang: 'en',
      setLang: (lang) => set({ lang }),
      t: (key) => {
        const currentLang = get().lang
        return TRANSLATIONS[currentLang]?.[key] || TRANSLATIONS['en']?.[key] || key
      },
    }),
    { name: 'skillsetu-language' }
  )
)
